### ISSUE TITLE
Most productive programming language

### ISSUE THREAD

**Issue by CarlMungazi** [ireade/ama#10]
Which programming language are you most productive in? What is your favourite feature of that language?

**Comment by ireade** [comment]
I'm the most productive in JavaScript, but that's because it's the only language (other than HTML/CSS) that I know *very* well. 

Although it's not really a feature, I love that JavaScript is **everywhere**. I can do so many things with it, not just build the frontend of websites.

**Comment by paulappz** [comment]
Ire. Remove  "the" from the first line above.

**Comment by ireade** [comment]
@paulappz It isn't a mistake.
