### ISSUE TITLE
Screenshot of you phone homescreen.

### ISSUE THREAD

**Issue by AchoArnold** [ireade/ama#11]

**Comment by ireade** [comment]
![Screen 1](https://cloud.githubusercontent.com/assets/8677283/24588785/60ec992e-17c7-11e7-9cc8-1ab373d78f58.PNG)
**Screen 1**

![Screen 2](https://cloud.githubusercontent.com/assets/8677283/24588788/683db028-17c7-11e7-8d44-1a601325fab7.PNG)
**Screen 2**
