### ISSUE TITLE
you have a bug

### ISSUE THREAD

**Issue by GitDema** [ireade/ama#14]
Hi Ire, in you tic tac toe game there is an error, my last step is victorious, but alert says me a draw.

![screenshot from 2017-08-17 18-05-21](https://user-images.githubusercontent.com/8056071/29419455-d78e4cfa-8377-11e7-845b-c4dcc2855647.png)

**Comment by ireade** [comment]
Hi @GitDema . Thanks for letting me know but that project is no longer being maintained. If you know how to fix the issue you're welcome to submit a PR to that repository :)
