### ISSUE TITLE
JS correction for your GitHub Contribution Graph example.

### ISSUE THREAD

**Issue by kingsbury** [ireade/ama#17]
Not a problem, just thought you'd like to know.
https://codepen.io/ire/pen/Legmwo/

On line 5: Change **Math.floor(Math.random() * 3)** to * 4.
Current code never uses the level 3 color style since only 0, 1, & 2 are ever assigned.

Great site and fun examples!

**Comment by ireade** [comment]
Thanks, it's already been fixed.
