### ISSUE TITLE
What do you suggest when switching to front-end development form UI Design and Development background?

### ISSUE THREAD

**Issue by zmmorabya** [ireade/ama#19]
2 min read ^_^

Hello Ire,

I know this is not the place to write this but I am a desperate case of a designer who wants to switch career to front-end.. I know a couple of designers who have done this shift before (it's not like something from outer space :D ) but their cases are slightly different as all of them, at some point, had stumbled upon an opportunity that have assisted greatly with their shift (whether as junior front-end positions or freelance task with a client who is willing to take the risk with someone of beginner experience).. For me, I wasn't able to find that kind of opportunity in addition to not being able to practice enough in my full-time position (I do UI design for web and mobile and UI Development without any hard core front-end development).. I was thinking should I quit my job and focus on learning and practicing front-end skills to be able to introduce my self as Front-end developer to career world or.. have no clue what other option do I have..

I am just too scared to leave my job and create a gab in my career path and not knowing how this step (quitting my job) will turn out? Am I going to succeed in learning? Or worse am I going to find another job in the career of my dream (I for sure don't want to be without a job.. I really love what I do especially the front-end part part in my tasks)..

Please if you have any pointers, guidance, recommendation, suggestion.. anything will be deep heartedly appreciated.

Thank you for the taking the time to go through my long message. ^_^

**Comment by ireade** [comment]
Hi @zmmorabya !

(sorry for taking so long to get to your question)

I think the best thing to do would be to start doing some projects on the side until you get more comfortable to leave your main career. I believe that if you're really interested and passionate about it, you can definitely make the career switch. 

You can also see my other question on [Resources for getting started with frontend development](https://github.com/ireade/ama/issues/13)
