### ISSUE TITLE
 Do you have any written story of your ups and downs as you progressed in this field?

### ISSUE THREAD

**Issue by THEozmic** [ireade/ama#2]
I like to read about how people who eventually succeed in life started out and how their journey has been. So do you have any stories about your journey since you started out? One starting from your great great great grandparents would be awesome.

**Comment by ireade** [comment]
Hi @THEozmic , I have an article about this which should be published soon. I'll share it here when it's published.

**Comment by THEozmic** [comment]
Okay, I'll be waiting to see it.

**Comment by ireade** [comment]
Hi @THEozmic !

Here is my story on how I started coding - ["An Unexpected Journey"](https://superyesmore.com/an-unexpected-journey-0795fee248fb985c748557ccb65a3494)
