### ISSUE TITLE
About sending push notifications section in your youtube channel

### ISSUE THREAD

**Issue by anggerdk** [ireade/ama#23]
Hello Ire. My name is Angger. I just have tried your simple push notification that you uploaded on youtube. I have tried your simple model here https://simply-notify.firebaseapp.com/, but nothing happen. The notification can't appear. Then, I follow your tutorial to figure out what actually happened and I got stuck in some parts. And then, when actually i almost done with the same source (from your github here) and i already deploy to https://simple-notif.firebaseapp.com/ the same things happen. The notifications didn't appear, and maybe i found the problem in part of functions, that you told to upload index.js there. In my function, actually with the same code as you, i found this : 
![image](https://user-images.githubusercontent.com/22940041/39671434-8b8cc6e4-5142-11e8-9993-fb553320cff3.png)

Actually i don't understand how to solve the property 'previous' that undefined. I hope you can help me please, because I'll using this to finish my undergraduate thesis, my topic is about the difference of push notification on web app and android app.
Best regards, Angger.

**Comment by huma1002** [comment]
hey,
I am also getting the same error :( 
did u get the solution?
please help

**Comment by ireade** [comment]
Hi. Please use the source code I provided in the simply-notify repository. That code works so you can work backwards from there. Unfortunately I don't have the time to debug every individual application, which is why I provide the completed source code for you to compare to.
