### ISSUE TITLE
reach out to girls

### ISSUE THREAD

**Issue by TiphaineMalorie** [ireade/ama#24]
Hi Ire!
What do you do for girls and women who look up to you and want to be like you? Would you really help someone you don't know ? Are you a mentor in your country?

**Comment by ireade** [comment]
Hi @TiphaineMalorie !

I'm not sure I understand the question. Is it my job to mentor women? I do write public articles and give talks, and work with female developer communities, including doing sponsorships, but it is by no means an obligation that I do that.
