### ISSUE TITLE
Would you work on a community-based project (for free)?

### ISSUE THREAD

**Issue by KidzGaming** [ireade/ama#25]
Hi, Ire.
I'm a 15 year-old Node.js developer from Lagos, working on DevX, a social network for developers, by developers. You can read about it [here](https://medium.com/@koredefashokun/what-is-devx-f7adc9274f79).

The aim is to bring all sorts of developers and designers together, to build a tool that they would use. Would be glad if you could join.

**Comment by ireade** [comment]
Hi @KidzGaming ! DevX looks cool, but I just don't have the time for another project right now. Good luck with it!
