### ISSUE TITLE
CAREER SWITCH

### ISSUE THREAD

**Issue by owolabiy** [ireade/ama#26]
Hi Ire,
I want to switch careers from finance to tech, but I'm not sure how to go about it, where to start or what to learn (first). I know I want to do what you do though. Do you have any advice on how I can get started, with no background in technology?. 

Thank you.

**Comment by THEozmic** [comment]
You can take a look at this: https://www.freecodecamp.org/

**Comment by ireade** [comment]
Hi @owolabiy ! Please see my other issue on [resources for getting started in frontend development](https://github.com/ireade/ama/issues/13)
