### ISSUE TITLE
pa11y running on windows throwing npm ERROR

### ISSUE THREAD

**Issue by bharatk89** [ireade/ama#27]
Hello Ire,

I recently saw the pa11y gitHub and started learning. It was really awesome. It is working as expected but after running the test I'm getting errors.
`npm ERR! code ELIFECYCLE
npm ERR! errno 2`
There is an error in start script. Any idea why is that happening?

Also if you can share us some examples on **how to do pa11y actions and html report that would be great.**

**Comment by ireade** [comment]
Hi @bharatk89 ! Please report this in the [pa11y github repo](https://github.com/pa11y/pa11y), I'm sure people working on the project there will be able to assist.
