### ISSUE TITLE
Would you strongly recommend getting a college degree in Nigeria as you did, if I wanted to build a career in programming?

### ISSUE THREAD

**Issue by THEozmic** [ireade/ama#3]

**Comment by ireade** [comment]
I didn't get a college degree in Nigeria, plus I didn't study anything to do with programming! I did Experimental Psychology for my undergraduate degree and Law for my Masters.

You don't need a college degree to build a career in programming, you just have to learn how to program!

**Comment by THEozmic** [comment]
Wow, I guess I got a wrong info on that one, thanks for clearing that up and answering the question.
