### ISSUE TITLE
OOP in js

### ISSUE THREAD

**Issue by stivonana** [ireade/ama#33]
HI ire! my name is Onana Steve from Cameroon and I really admire you. I currently learning web development at FreeCodeCamp and **I want to know where I can find beginner-friendly code written in OOP-style to read?** I've already studied basics of OOP but I feel like I can't write in that style thus the need to read through more experienced developers code. I've already watched your Youtube video on Realtime Form validation (it is awesome) but I need more. Thanks !!! MY email is onanasteve94@gmail.com

**Comment by THEozmic** [comment]
Hey, you should check this out: https://github.com/getify/You-Dont-Know-JS/

**Comment by ireade** [comment]
Hi @stivonana ! Unfortunately I don't know any resources specifically for OOP programming. I think the linkgiven by @THEozmic looks good though!
