### ISSUE TITLE
Request for mentorship

### ISSUE THREAD

**Issue by haywhy43** [ireade/ama#35]
Hi Ire, 
My name is Ayo, I'm a student of computer sciences in the university of Lagos. I'm very passionate about programming and I've been trying to do my part in improving on myself in web development, I even took an online course that treated web development and based on the basics reactjs for the front-end and some other things. But now I'm currently confused on what to do about my situation as I don't know what to do again, that is why I'm reaching out to you to seek advice form someone who is a senior in the field

**Comment by THEozmic** [comment]
You should build something with the skills you have. Don't stop learning, keep taking more courses and building stuff with what you learn. When you are building or engaged in learning and you face issues, you can always reach out on those specific issues. This is more practical and useful to you.

You should also read this: https://github.com/getify/You-Dont-Know-JS/

I hope this was helpful.

**Comment by ireade** [comment]
Hi @haywhy43 !

Please see my other issue on [resources for getting started with web development](https://github.com/ireade/ama/issues/13).
