### ISSUE TITLE
Question about your example: A More Accessible Multi-Level Dropdown Navigation

### ISSUE THREAD

**Issue by tuyetCraig** [ireade/ama#37]
Hello, I googled and got your example of multi-level dropdown menu.  
https://bitsofco.de/accessible-multi-level-dropdown-navigation/
I want to use it for my school project.  I am a novice when it come to CSS and javascript.  I like that you take into the issues with accessibility.  How would I modified the javascript/CSS so that when you click on "Level 3", it will expand the submenu instead of the current method of hovering.  However, I would like it to continue to have the submenu under Level 3 (Example Link) be expanded when the event is a hover (mouseover).  I hope you can help me and get back to me soon so I can finish up my school project.  Thank you.

Tuyet

**Comment by ireade** [comment]
Hi @tuyetCraig ! Please raise an issue on that repository, this is more of an AMA for questions not about specific projects
