### ISSUE TITLE
Your journey 

### ISSUE THREAD

**Issue by Toyurc** [ireade/ama#38]
I would like to ask about your journey so far as a frontend engineer, what would you say has made you stand out, and how did you become a better software engineer. I mean in terms of things you had to learn, best practices and whatnots. Thanks.

**Comment by ireade** [comment]
Hi @Toyurc ! I've done a few interviews where I answer these questions. You can find one here - https://townhall.hashnode.com/women-in-tech-ire-aderinokun-cjzjhrcqp000t66s19xikzic4
