### ISSUE TITLE
Request to translate your articles

### ISSUE THREAD

**Issue by hellodeloo** [ireade/ama#39]
Hello Ire,

Happy to meet you.

I introduce myself, my name is David, I am a French freelance front-end developer.
I have a [portfolio website](https://www.hellodeloo.com/) where I will soon open a blog section and I want to start by translating certain article in English.

Among these articles, I would like to translate 4 of your recent articles.
"A look at CSS Resets in 2018", "What is the Shadow DOM", "How to use the tabindex attribute" and "Everything about CSS environment variables".

So I'm contacting you to find out if you would like me to translate your articles on my blog?
Of course I would quote the source of these articles translated and I put a link to the original article and your portfolio.
What do you think ?

Regards,

**Comment by ireade** [comment]
Hi @hellodeloo ! Please see https://bitsofco.de/translations/
