### ISSUE TITLE
I'd wear a Wig! :)

### ISSUE THREAD

**Issue by Damian-ynote** [ireade/ama#43]
Would grow hips if I could, just to get a shot at applying to your Udacity Nano Degree Scholarship and I know this is out of place but if there's the slightest bit of a chance I'd really like to get sponsored for a FrontEnd Dev course and I'd definitely wear a wig :)

**Comment by ireade** [comment]
This is a very offensive thing to say. How can you possibly think it is okay or funny to reduce a gender to long hair and hips? This is clearly why I need to give these scholarships to women only.
