### ISSUE TITLE
Number of Women GDEs in Africa 

### ISSUE THREAD

**Issue by CodeReign** [ireade/ama#47]
Hello Ire,

My name is Grace and I have been following you on Twitter since I see you as role model to me. I learn a lot from your posts. However, the other day I was wondering how many women GDEs we have in Africa. I know you are a GDE but I am not aware of any other women GDEs in Africa. Please tell me if there are others. Thank you.

**Comment by ireade** [comment]
Hi @kahinga99 ! I'm not sure of this answer, you'll have to look on the website
