### ISSUE TITLE
Name of the Artist

### ISSUE THREAD

**Issue by camckin10** [ireade/ama#48]
Hello! 
I discovered you through 'The Accessibility Cheatsheet', on  bitsofco.de. The cheatsheet led me to check out your personal website/porfolio.

In the 'Contact' section of your portfolio, there is a really cool animated picture of you. 
I wanted to know who was the artist who did that animation, and, if this individual/company is taking new clients? 

Thank you!

Chelsey

**Comment by ireade** [comment]
https://studioofmode.com
