### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by eromzy** [ireade/ama#7]
Sure you having a great day? just stumbled upon you/you site in the funniest of ways. saw a screen grab where you wrote about the challenges female techies face and i couldn't stop laughing. 

Pls i'd love to know how long you've been a developer, and also i'd love to be one. how do i go about learning it? can i maybe learn myself or i'd need a tutor?

Would really appreciate if i can get a reply. 

Thanks a lot. by the way, you look good.  Have a great day.

PS; I just copied and pasted from the earlier mail i sent. hope that's okay

**Comment by ireade** [comment]
Hi @eromzy !

You can learn development just by playing around with it. Try doing online tutorials to get started and see if you're interested enough to keep on going. That is how I started. You don't necessarily need a tutor (I didn't have one), but if that is the way you learn better then you can try studying Engineering more formally, at a university or something.
