### ISSUE TITLE
Guideline from conceptualization to development of an idea

### ISSUE THREAD

**Issue by Peeyou** [ireade/ama#9]
I am in front-end development. I am learning more everyday.

Please how do you conceptualize an idea into workable plans. For example you are told, "develop a social networking website". The person telling you doesn't know much about it, only that she needs it done awesomely. So you are to do a brief from your research and do designs and propose features.

How would you begin it all? What would you do first and next?

Thanks and i appreciate.

**Comment by ireade** [comment]
Hi @Peeyou ! This is a bit of a larger question than I can answer properly here. But to give a brief answer, you just need to break down the concept into smaller tasks and look at them individually.
